from __future__ import annotations
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Union

from fpdf import FPDF
from fpdf.enums import XPos, YPos


class SecurityReportPDF(FPDF):
    """Custom PDF generator for CryptoJackGuard Enterprise Security Reports."""

    def header(self) -> None:
        # Dark navy header banner
        self.set_fill_color(24, 32, 47)
        self.rect(0, 0, 210, 26, "F")

        # Title
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.set_xy(12, 6)
        self.cell(0, 8, "CryptoJackGuard Enterprise Security Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Subtitle
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(180, 195, 215)
        self.set_xy(12, 14)
        self.cell(0, 6, "Automated Cryptojacking Threat Assessment & Telemetry Audit", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Reset text color and positioning
        self.set_text_color(40, 40, 40)
        self.set_y(32)

    def footer(self) -> None:
        self.set_y(-18)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        # Line separator
        self.set_draw_color(200, 200, 200)
        self.line(12, 280, 198, 280)
        # Footer text
        self.set_xy(12, 282)
        self.cell(0, 6, f"Generated by CryptoJackGuard Cloud Defense System | Page {self.page_no()}/{{nb}}", align="C")


def _extract_record_dict(alert: Union[Dict[str, Any], Any]) -> Dict[str, Any]:
    """Normalize AlertRecord ORM object or dict into a standard dictionary."""
    if hasattr(alert, "to_dict"):
        return alert.to_dict()
    if isinstance(alert, dict):
        return alert
    # Fallback attribute extraction
    return {
        "timestamp": getattr(alert, "timestamp", None),
        "process_name": getattr(alert, "process_name", getattr(alert, "name", "unknown")),
        "pid": getattr(alert, "pid", None),
        "risk_score": getattr(alert, "risk_score", getattr(alert, "score", 0.0)),
        "ml_confidence": getattr(alert, "ml_confidence", 0.0),
        "action_taken": getattr(alert, "action_taken", getattr(alert, "response_action", "alert")),
        "details": getattr(alert, "details", {}),
    }


def generate_security_report(
    alerts: List[Any],
    output_path: Optional[Union[Path, str]] = None,
    system_metrics: Optional[Dict[str, Any]] = None,
) -> Union[str, bytes]:
    """Generate a comprehensive enterprise PDF security report for CryptoJackGuard.

    Args:
        alerts: List of AlertRecord model instances or alert dictionaries.
        output_path: Target PDF file destination (if None, returns in-memory bytes).
        system_metrics: Optional dictionary containing live CPU, memory, GPU metrics.

    Returns:
        String path of the generated PDF report, or raw bytes if output_path is None.
    """
    normalized_alerts = [_extract_record_dict(a) for a in alerts]
    total_alerts = len(normalized_alerts)
    high_risk_count = sum(1 for a in normalized_alerts if float(a.get("risk_score") or a.get("score") or 0.0) >= 60.0)
    mitigations_count = sum(1 for a in normalized_alerts if a.get("action_taken") and str(a.get("action_taken")).lower() != "alert")
    avg_score = (sum(float(a.get("risk_score") or a.get("score") or 0.0) for a in normalized_alerts) / total_alerts) if total_alerts > 0 else 0.0

    pdf = SecurityReportPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=22)
    pdf.add_page()

    # 1. Report Metadata
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(100, 6, f"Generated At: {now_str}", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_font("Helvetica", "B", 9)
    if high_risk_count > 0:
        pdf.set_text_color(180, 50, 50)
    else:
        pdf.set_text_color(50, 140, 50)
    pdf.cell(0, 6, f"Status: {'THREATS DETECTED' if high_risk_count > 0 else 'NORMAL / PROTECTED'}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="R")
    pdf.ln(3)

    # 2. Executive Summary Metrics Cards
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(24, 32, 47)
    pdf.cell(0, 7, "Executive Telemetry Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(220, 225, 235)

    card_width = 44
    card_height = 18
    y_start = pdf.get_y()

    metrics = system_metrics or {}
    if metrics:
        cards = [
            ("CPU / Memory Usage", f"{metrics.get('cpu_percent', 0.0):.1f}% / {metrics.get('memory_percent', 0.0):.1f}%", (245, 247, 250)),
            ("High-Risk Alerts", str(high_risk_count), (255, 243, 243) if high_risk_count > 0 else (245, 247, 250)),
            ("Mitigations Executed", str(mitigations_count), (243, 249, 244) if mitigations_count > 0 else (245, 247, 250)),
            ("Average Risk Score", f"{avg_score:.1f}/100", (245, 247, 250)),
        ]
    else:
        cards = [
            ("Total Events", str(total_alerts), (245, 247, 250)),
            ("High-Risk Alerts", str(high_risk_count), (255, 243, 243) if high_risk_count > 0 else (245, 247, 250)),
            ("Mitigations Executed", str(mitigations_count), (243, 249, 244) if mitigations_count > 0 else (245, 247, 250)),
            ("Average Risk Score", f"{avg_score:.1f}/100", (245, 247, 250)),
        ]

    for idx, (label, val, fill_rgb) in enumerate(cards):
        x_pos = 12 + (idx * (card_width + 4))
        pdf.set_xy(x_pos, y_start)
        pdf.set_fill_color(*fill_rgb)
        pdf.rect(x_pos, y_start, card_width, card_height, "DF")

        pdf.set_xy(x_pos + 2, y_start + 2)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(100, 110, 125)
        pdf.cell(card_width - 4, 4, label, align="C")

        pdf.set_xy(x_pos + 2, y_start + 7)
        pdf.set_font("Helvetica", "B", 12)
        if label == "High-Risk Alerts" and high_risk_count > 0:
            pdf.set_text_color(200, 30, 30)
        else:
            pdf.set_text_color(24, 32, 47)
        pdf.cell(card_width - 4, 7, val, align="C")

    pdf.set_y(y_start + card_height + 8)

    # 3. Threat Assessment & System Findings
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(24, 32, 47)
    pdf.cell(0, 7, "Threat Assessment & Incident Records", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)

    if not normalized_alerts:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 8, "No security alerts recorded. System is operating normally.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    else:
        # Table Header
        pdf.set_fill_color(35, 45, 65)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)

        cols = [
            ("Timestamp", 35),
            ("Process Name", 40),
            ("PID", 16),
            ("Risk Score", 22),
            ("Action", 30),
            ("Details / Reasons", 43),
        ]

        for label, width in cols:
            pdf.cell(width, 7, label, border=1, fill=True, align="C")
        pdf.ln()

        # Table Rows
        pdf.set_font("Helvetica", "", 7.5)
        for i, a in enumerate(normalized_alerts[:40]):  # Top recent alerts
            # Alternating background color
            fill = (i % 2 == 1)
            pdf.set_fill_color(248, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
            pdf.set_text_color(30, 30, 30)

            ts_raw = str(a.get("timestamp") or "N/A")[:19].replace("T", " ")
            proc_name = str(a.get("process_name") or a.get("name") or "unknown")[:22]
            pid_str = str(a.get("pid") or "-")
            score_val = float(a.get("risk_score") or a.get("score") or 0.0)
            score_str = f"{score_val:.1f}"
            action_str = str(a.get("action_taken") or a.get("response_action") or "Alert")[:18]

            details_obj = a.get("details") or {}
            reasons = details_obj.get("reasons") or a.get("reasons") or []
            if isinstance(reasons, list):
                reasons_str = "; ".join(str(r) for r in reasons[:2])[:28]
            else:
                reasons_str = str(reasons)[:28]
            if not reasons_str:
                reasons_str = "High CPU / Telemetry"

            # Render row cells
            pdf.cell(35, 6, ts_raw, border=1, fill=fill)
            pdf.cell(40, 6, proc_name, border=1, fill=fill)
            pdf.cell(16, 6, pid_str, border=1, fill=fill, align="C")

            # Color risk score cell if high
            if score_val >= 60.0:
                pdf.set_text_color(180, 20, 20)
                pdf.cell(22, 6, score_str, border=1, fill=fill, align="C")
                pdf.set_text_color(30, 30, 30)
            else:
                pdf.cell(22, 6, score_str, border=1, fill=fill, align="C")

            pdf.cell(30, 6, action_str, border=1, fill=fill)
            pdf.cell(43, 6, reasons_str, border=1, fill=fill)
            pdf.ln()

    # Output PDF: return bytes if output_path is None, else write to file
    if output_path is not None:
        resolved_path = Path(output_path)
        resolved_path.parent.mkdir(parents=True, exist_ok=True)
        pdf.output(str(resolved_path))
        return str(resolved_path)

    return bytes(pdf.output())


if __name__ == "__main__":
    generate_security_report([])
